export enum ActionType {
	CREATE_ITEM = "CREATE_ITEM",
	TOGGLE_COMPLETE = "TOGGLE_COMPLETE",
	REMOVE_ITEM = "REMOVE_ITEM",
	UPDATE_INPUT_VALUE = "UPDATE_INPUT_VALUE",
	COMPLETE_ALL_ITEMS = "COMPLETE_ALL_ITEMS",
	REMOVE_ALL_COMPLETED_ITEMS = "REMOVE_ALL_COMPLETED_ITEMS",
	SET_ITEM_VISIBILITY_STATUS = "SET_ITEM_VISIBILITY_STATUS",
}

export enum ItemVisibilityStatus {
	ALL = "ALL",
	ACTIVE_ONLY = "ACTIVE_ONLY",
	COMPLETED_ONLY = "COMPLETED_ONLY",
}
